/* tslint:disable */
/* eslint-disable */
/**
 * Mediva API
 * Specification of the Mediva API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@mediva.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateFlow,
  CreateFlowFromFlowTemplateRequest,
  Flow,
  FlowEntry,
  FlowHistory,
} from '../models/index';

export interface CreateFlowRequest {
    createFlow: CreateFlow;
}

export interface CreateFlowFromFlowTemplateOperationRequest {
    createFlowFromFlowTemplateRequest: CreateFlowFromFlowTemplateRequest;
}

export interface DeleteFlowByIdRequest {
    flowId: string;
}

export interface GetFlowByPatientRequest {
    patientId: string;
}

export interface SaveFlowRequest {
    flowId: string;
}

export interface UpdateFlowEntryRequest {
    flowId: string;
    flowEntry: FlowEntry;
}

/**
 * FlowApi - interface
 * 
 * @export
 * @interface FlowApiInterface
 */
export interface FlowApiInterface {
    /**
     * 
     * @summary Create a flow for a patient in a hospital
     * @param {CreateFlow} createFlow 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    createFlowRaw(requestParameters: CreateFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>>;

    /**
     * Create a flow for a patient in a hospital
     */
    createFlow(createFlow: CreateFlow, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow>;

    /**
     * 
     * @summary Create a Flow from a Flow Template
     * @param {CreateFlowFromFlowTemplateRequest} createFlowFromFlowTemplateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    createFlowFromFlowTemplateRaw(requestParameters: CreateFlowFromFlowTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>>;

    /**
     * Create a Flow from a Flow Template
     */
    createFlowFromFlowTemplate(createFlowFromFlowTemplateRequest: CreateFlowFromFlowTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow>;

    /**
     * 
     * @summary Delete a flow by ID
     * @param {string} flowId ID of the flow to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    deleteFlowByIdRaw(requestParameters: DeleteFlowByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a flow by ID
     */
    deleteFlowById(flowId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get flow for a patient in a hospital
     * @param {string} patientId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    getFlowByPatientRaw(requestParameters: GetFlowByPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>>;

    /**
     * Get flow for a patient in a hospital
     */
    getFlowByPatient(patientId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow>;

    /**
     * 
     * @summary Save flow into flow history
     * @param {string} flowId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    saveFlowRaw(requestParameters: SaveFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FlowHistory>>;

    /**
     * Save flow into flow history
     */
    saveFlow(flowId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FlowHistory>;

    /**
     * 
     * @summary Update a specific flow entry
     * @param {string} flowId 
     * @param {FlowEntry} flowEntry 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FlowApiInterface
     */
    updateFlowEntryRaw(requestParameters: UpdateFlowEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FlowEntry>>;

    /**
     * Update a specific flow entry
     */
    updateFlowEntry(flowId: string, flowEntry: FlowEntry, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FlowEntry>;

}

/**
 * 
 */
export class FlowApi extends runtime.BaseAPI implements FlowApiInterface {

    /**
     * Create a flow for a patient in a hospital
     */
    async createFlowRaw(requestParameters: CreateFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>> {
        if (requestParameters['createFlow'] == null) {
            throw new runtime.RequiredError(
                'createFlow',
                'Required parameter "createFlow" was null or undefined when calling createFlow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createFlow'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create a flow for a patient in a hospital
     */
    async createFlow(createFlow: CreateFlow, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow> {
        const response = await this.createFlowRaw({ createFlow: createFlow }, initOverrides);
        return await response.value();
    }

    /**
     * Create a Flow from a Flow Template
     */
    async createFlowFromFlowTemplateRaw(requestParameters: CreateFlowFromFlowTemplateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>> {
        if (requestParameters['createFlowFromFlowTemplateRequest'] == null) {
            throw new runtime.RequiredError(
                'createFlowFromFlowTemplateRequest',
                'Required parameter "createFlowFromFlowTemplateRequest" was null or undefined when calling createFlowFromFlowTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/create-from-template`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createFlowFromFlowTemplateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create a Flow from a Flow Template
     */
    async createFlowFromFlowTemplate(createFlowFromFlowTemplateRequest: CreateFlowFromFlowTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow> {
        const response = await this.createFlowFromFlowTemplateRaw({ createFlowFromFlowTemplateRequest: createFlowFromFlowTemplateRequest }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a flow by ID
     */
    async deleteFlowByIdRaw(requestParameters: DeleteFlowByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['flowId'] == null) {
            throw new runtime.RequiredError(
                'flowId',
                'Required parameter "flowId" was null or undefined when calling deleteFlowById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/{flowId}`;
        urlPath = urlPath.replace(`{${"flowId"}}`, encodeURIComponent(String(requestParameters['flowId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a flow by ID
     */
    async deleteFlowById(flowId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFlowByIdRaw({ flowId: flowId }, initOverrides);
    }

    /**
     * Get flow for a patient in a hospital
     */
    async getFlowByPatientRaw(requestParameters: GetFlowByPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Flow>> {
        if (requestParameters['patientId'] == null) {
            throw new runtime.RequiredError(
                'patientId',
                'Required parameter "patientId" was null or undefined when calling getFlowByPatient().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['patientId'] != null) {
            queryParameters['patientId'] = requestParameters['patientId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/get-by-patient`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get flow for a patient in a hospital
     */
    async getFlowByPatient(patientId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Flow> {
        const response = await this.getFlowByPatientRaw({ patientId: patientId }, initOverrides);
        return await response.value();
    }

    /**
     * Save flow into flow history
     */
    async saveFlowRaw(requestParameters: SaveFlowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FlowHistory>> {
        if (requestParameters['flowId'] == null) {
            throw new runtime.RequiredError(
                'flowId',
                'Required parameter "flowId" was null or undefined when calling saveFlow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/save/{flowId}`;
        urlPath = urlPath.replace(`{${"flowId"}}`, encodeURIComponent(String(requestParameters['flowId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Save flow into flow history
     */
    async saveFlow(flowId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FlowHistory> {
        const response = await this.saveFlowRaw({ flowId: flowId }, initOverrides);
        return await response.value();
    }

    /**
     * Update a specific flow entry
     */
    async updateFlowEntryRaw(requestParameters: UpdateFlowEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FlowEntry>> {
        if (requestParameters['flowId'] == null) {
            throw new runtime.RequiredError(
                'flowId',
                'Required parameter "flowId" was null or undefined when calling updateFlowEntry().'
            );
        }

        if (requestParameters['flowEntry'] == null) {
            throw new runtime.RequiredError(
                'flowEntry',
                'Required parameter "flowEntry" was null or undefined when calling updateFlowEntry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("http-bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/flow/update-entry/{flowId}`;
        urlPath = urlPath.replace(`{${"flowId"}}`, encodeURIComponent(String(requestParameters['flowId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['flowEntry'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update a specific flow entry
     */
    async updateFlowEntry(flowId: string, flowEntry: FlowEntry, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FlowEntry> {
        const response = await this.updateFlowEntryRaw({ flowId: flowId, flowEntry: flowEntry }, initOverrides);
        return await response.value();
    }

}
